name: dartclub_lint
description: Dart analyzer rules, based on pedantic
version: 0.3.0
homepage: https://github.com/dartclub/linter_rules

environment:
  sdk: ">=2.7.0 <3.0.0"

dev_dependencies:
  pedantic: ^1.11.1

